
generate:
	remoto generate ./definition ../templates/go/remotohttpjson/server.go.plush -o ./go/server/server.go
	remoto generate ./definition ../templates/go/remotohttpjson/client.go.plush -o ./go/client/client.go

install:
	cd .. ; go install
