// Code generated by Remoto; DO NOT EDIT.

// Package files contains the HTTP server for files services.
package files

import (
	"context"
	"fmt"
	"net/http"
	"os"

	"github.com/machinebox/remoto/go/remotohttp"
	"github.com/machinebox/remoto/remototypes"
	"github.com/pkg/errors"
)

// Images provides image services.
type Images interface {
	Flip(context.Context, *FlipRequest) (*FlipResponse, error)
}

// Run is the simplest way to run the services.
func Run(addr string,
	images Images,
) error {
	server := New(
		images,
	)
	if err := server.Describe(os.Stdout); err != nil {
		return errors.Wrap(err, "describe service")
	}
	if err := http.ListenAndServe(addr, server); err != nil {
		return err
	}
	return nil
}

// New makes a new remotohttp.Server with the specified services
// registered.
func New(
	images Images,
) *remotohttp.Server {
	server := &remotohttp.Server{
		OnErr: func(w http.ResponseWriter, r *http.Request, err error) {
			fmt.Fprintf(os.Stderr, "%s %s: %s\n", r.Method, r.URL.Path, err.Error())
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}

	RegisterImagesServer(server, images)
	return server
}

// RegisterImagesServer registers a Images with a remotohttp.Server.
func RegisterImagesServer(server *remotohttp.Server, service Images) {
	srv := &httpImagesServer{
		service: service,
		server:  server,
	}

	server.Register("/remoto/Images.Flip", http.HandlerFunc(srv.handleFlip))

}

// FlipResponse is the response for Images.Flip.
type FlipResponse struct {
	FlippedImage remototypes.File `json:"flipped_image"`

	// Error is an error message if one occurred.
	Error string `json:"error"`
}

// FlipRequest is the request for Images.Flip.
type FlipRequest struct {
	Image remototypes.File `json:"image"`
}

// httpImagesServer is an internal type that provides an
// HTTP wrapper around Images.
type httpImagesServer struct {
	// service is the Images being exposed by this
	// server.
	service Images
	// server is the remotohttp.Server that this server is
	// registered with.
	server *remotohttp.Server
}

// handleFlip is an http.Handler wrapper for Images.Flip.
func (srv *httpImagesServer) handleFlip(w http.ResponseWriter, r *http.Request) {
	var reqs []*FlipRequest
	if err := remotohttp.Decode(r, &reqs); err != nil {
		srv.server.OnErr(w, r, err)
		return
	}
	resps := make([]FlipResponse, len(reqs))
	for i := range reqs {
		resp, err := srv.service.Flip(r.Context(), reqs[i])
		if err != nil {
			resps[i].Error = err.Error()
			continue
		}
		resps[i] = *resp
	}
	if err := remotohttp.Encode(w, r, http.StatusOK, resps); err != nil {
		srv.server.OnErr(w, r, err)
		return
	}
}

// this is here so we don't get a compiler complaint about
// importing remototypes but not using it.
var _ = remototypes.File("ignore me")
